const LABELS_METADATA = [
  {label: 'area: cdk/a11y', contains: ['a11y', 'focustrap', 'liveannouncer', 'focus-trap', 'focus monitor', 'focusmonitor'],},
  {label: 'area: cdk/accordion', contains: ['accordion']},
  {label: 'area: cdk/bidi', contains: ['bidi', 'direction']},
  {label: 'area: cdk/clipboard', contains: ['clipboard']},
  {label: 'area: cdk/coercion', contains: ['coercion']},
  {label: 'area: cdk/collections', contains: ['collections', 'selectionmodel']},
  {label: 'area: cdk/drag-drop', contains: ['drag-drop', 'drag']},
  {label: 'area: cdk/keycodes', contains: ['keycodes']},
  {label: 'area: cdk/layout', contains: ['layout']},
  {label: 'area: cdk/observers', contains: ['observers']},
  {label: 'area: cdk/overlay', contains: ['overlay', 'fullscreen']},
  {label: 'area: cdk/platform', contains: ['platform']},
  {label: 'area: cdk/popover-edit', contains: ['popover-edit']},
  {label: 'area: cdk/portal', contains: ['portal']},
  {label: 'area: cdk/schematics', contains: ['schematics']},
  {label: 'area: cdk/scrolling', contains: ['scroll']},
  {label: 'area: cdk/stepper', contains: ['stepper']},
  {label: 'area: cdk/table', contains: ['table']},
  {label: 'area: cdk/testing', contains: ['testing']},
  {label: 'area: cdk/text-field', contains: ['text-field']},
  {label: 'area: cdk/tree', contains: ['tree']},
  {label: 'area: dev-infra', contains: ['dev-infra']},
  {label: 'area: dgeni', contains: ['dgeni']},
  {label: 'area: google-maps', contains: ['google-maps', 'google map']},
  {label: 'area: material.angular.io', contains: ['material.angular.io']},
  {label: 'area: material/autocomplete', contains: ['autocomplete', 'auto complete']},
  {label: 'area: material/badge', contains: ['badge']},
  {label: 'area: material/bottom-sheet', contains: ['bottom-sheet']},
  {label: 'area: material/button', contains: ['button']},
  {label: 'area: material/button-toggle', contains: ['button-toggle', 'button toggle', 'toggle button']},
  {label: 'area: material/card', contains: ['card']},
  {label: 'area: material/checkbox', contains: ['checkbox', 'check-box']},
  {label: 'area: material/chips', contains: ['chip']},
  {label: 'area: material/core', contains: ['core']},
  {label: 'area: material/datepicker', contains: ['datepicker', 'calendar']},
  {label: 'area: material/dialog', contains: ['dialog']},
  {label: 'area: material/divider', contains: ['divider']},
  {label: 'area: material/expansion', contains: ['expansion']},
  {label: 'area: material/form-field', contains: ['form-field', 'formfield', 'form field']},
  {label: 'area: material/grid-list', contains: ['grid-list']},
  {label: 'area: material/icon', contains: ['icon']},
  {label: 'area: material/input', contains: ['input', 'textarea']},
  {label: 'area: material/list', contains: ['list']},
  {label: 'area: material/menu', contains: ['menu']},
  {label: 'area: material/paginator', contains: ['paginator']},
  {label: 'area: material/progress-bar', contains: ['progress-bar', 'progress bar']},
  {label: 'area: material/progress-spinner', contains: ['progress-spinner', 'progress spinner', 'spinner']},
  {label: 'area: material/radio', contains: ['radio']},
  {label: 'area: material/select', contains: ['select']},
  {label: 'area: material/sidenav', contains: ['sidenav', 'drawer']},
  {label: 'area: material/slide-toggle', contains: ['slide-toggle']},
  {label: 'area: material/slider', contains: ['slider']},
  {label: 'area: material/snack-bar', contains: ['snack-bar', 'snackbar']},
  {label: 'area: material/sort', contains: ['sort']},
  {label: 'area: material/stepper', contains: ['stepper']},
  {label: 'area: material/table', contains: ['table']},
  {label: 'area: material/tabs', contains: ['tab']},
  {label: 'area: material/testing', contains: ['testing']},
  {label: 'area: material/toolbar', contains: ['toolbar']},
  {label: 'area: material/tooltip', contains: ['tooltip']},
  {label: 'area: material/tree', contains: ['tree']},
  {label: 'area: ng-add', contains: ['ng-add']},
  {label: 'area: ng-generate', contains: ['ng-generate']},
  {label: 'area: ng-update', contains: ['ng-update']},
  {label: 'area: theming', contains: ['theming', 'theme']},
  {label: 'area: youtube-player', contains: ['youtube']},
];
